# Generated by Django 4.2.4 on 2023-08-04 13:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0003_autor"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name": "Autor", "verbose_name_plural": "Autores"},
        ),
    ]
