# Generated by Django 4.2.4 on 2023-08-11 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0005_livro"),
    ]

    operations = [
        migrations.AddField(
            model_name="livro",
            name="autores",
            field=models.ManyToManyField(related_name="livros", to="livraria.autor"),
        ),
    ]
