# Generated by Django 4.2.4 on 2023-08-17 16:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("livraria", "0006_livro_autores"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="autor",
            options={"verbose_name_plural": "Autores"},
        ),
        migrations.AlterField(
            model_name="autor",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
